Use strings for key, value in tags
Ensure that the keys and values for user supplied tags are converted to
strings. Some users of this library complained about the difficulty of
tracking down errors like the following:

```
registry polling failed: <class 'TypeError'>
Traceback (most recent call last):
  File "/apps/titusjob/lib/python3.6/site-packages/spectator/registry.py", line 222, in _run
    self._function()
  File "/apps/titusjob/lib/python3.6/site-packages/spectator/registry.py", line 141, in _publish
    self._send_batch(snapshot[i:end])
  File "/apps/titusjob/lib/python3.6/site-packages/spectator/registry.py", line 127, in _send_batch
    json = self._measurements_to_json(batch)
  File "/apps/titusjob/lib/python3.6/site-packages/spectator/registry.py", line 170, in _measurements_to_json
    strings = self._build_string_table(payload, data)
  File "/apps/titusjob/lib/python3.6/site-packages/spectator/registry.py", line 161, in _build_string_table
    keys.sort()
TypeError: '<' not supported between instances of 'bool' and 'str'
```

When there are many dependencies they do not own directly.